spring:
  application:
    name: gedtotal-custody-service
  kafka:
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "br.com.arquivototal.gedtotalcustody.domain.event"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8092

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true

app:
  security:
    oauth2-enabled: false
  internal-api:
    gedtotalapi-base-url: http://localhost:8080
  kafka:
    topics:
      custody-request: custodia.anchor.request
      custody-result: custodia.anchor.result
      custody-failure: custodia.anchor.failure
