apiVersion: v1
kind: Secret
metadata:
  name: gedtotal-custody-service-secrets
  namespace: gedtotalap-apps
type: Opaque
stringData:
  APP_SECURITY_INTERNAL_SHARED_TOKEN: "change-me"
  BLOCKCHAIN_PRIVATE_KEY: "change-me"
  BLOCKCHAIN_RPC_URL: "change-me"
